### ISSUE TITLE
Is it possible to collide obstacles during optimization?

### ISSUE THREAD

**Issue by ruiqini** [HKUST-Aerial-Robotics/grad_traj_optimization#13]
Hi, thank you very much for release the code, it is really helpful. Here is my problem.
When I am running a case using a cylinder obstacle and I set several waypoints around the cylinder.

Here is the initial trajectory. There is no collision.
![Screenshot from 2020-09-16 21-16-23](https://user-images.githubusercontent.com/19708491/93408827-811f8a00-f863-11ea-9a69-b3aab78edc45.png)

Here is the trajectory after first step optimization, and there is no collision too.
![Screenshot from 2020-09-16 21-20-07](https://user-images.githubusercontent.com/19708491/93408930-be841780-f863-11ea-9950-70c4a9c4f8be.png)

While after second step optimization, the trajectory has collision with the obstacle.
![Screenshot from 2020-09-16 21-21-55](https://user-images.githubusercontent.com/19708491/93408993-df4c6d00-f863-11ea-8098-cde1b1f73c5c.png)

Is it possible to have such a condition? Or it is because I am using some wrong parameters. Thank you very much for your time.

**Comment by ZbyLGsc** [comment]
Yes it is possible. The optimization is in nonlinear form, so it may get stuck in infeasible minima.

In the first step, the collision cost has higher weight, while in the second step more emphasis is put on smoothness, so it might cause collision.

**Comment by ruiqini** [comment]
Thanks for your response, it is clear to me. I will adjust this parameter and test more cases.
