### ISSUE TITLE
Trajectory inconsistent with the demonstration?

### ISSUE THREAD

**Issue by Lu-tju** [HKUST-Aerial-Robotics/grad_traj_optimization#16]
I compile the code in ubuntu 20.04 with NLopt 2.7.1. However, the trajectory generated by running ` roslaunch grad_traj_optimization text_input.launch` looks like:

![Screenshot from 2023-05-29 22-14-29](https://github.com/HKUST-Aerial-Robotics/grad_traj_optimization/assets/57125479/aadf2f24-ae21-434f-b07f-1a2de6e9a9d1)
and is inconsistent with the demonstration. Does anyone meet the same problem?
Thanks!

have solved:
I modified the params in text_input.launch to be same with random.launch and looks no problems, thanks!

**Comment by VincentHFZ** [comment]
您好，您的邮件我已经接收到，我会尽快处理--黄发展
