### ISSUE TITLE
Is this procedure suitable for ground mobile robots?

### ISSUE THREAD

**Issue by root29** [HKUST-Aerial-Robotics/grad_traj_optimization#4]
Hi，Thanks for you great works.
Is the procedure suitable for service mobile robots?

**Comment by USTfgaoaa** [comment]
@root29 Yes it's well suitable. By the way, you can also add a cost term on the curvature, which may be desirable for ground robots.

**Comment by jh-kandarp** [comment]
Hi, 
Can you elaborate further how to add cost on the curvature ? 
As the cost is computed in the closed form solution for each dimension separably. 
Thank you very much
