### ISSUE TITLE
Integration with octomap

### ISSUE THREAD

**Issue by Changliu52** [HKUST-Aerial-Robotics/grad_traj_optimization#5]
Hi,
Thanks for sharing the nice code.
I wonder do you have any suggestion how to integrate it with octomap?

Many thanks.

Kind Regards,
Chang

**Comment by AlexisTM** [comment]
@Changliu52 Hey, isn't it octomap that's used here? https://www.bilibili.com/video/av16979476/

**Comment by USTfgaoaa** [comment]
@AlexisTM No there is no Octo-map used in that paper. Actually, there are just voxels visualized in the video.

**Comment by USTfgaoaa** [comment]
@Changliu52 Integration with Octo-map just requires a different way to query the distance value in a cost field. You may consider to additionally maintain a local distance field for optimizing the trajectory.

**Comment by Changliu52** [comment]
Thank you very much for the reply.
Ok. In this case, it doesn't have to be an octomap.

I assume it has its own built-in mapping engine. If I have pose information from VINSMONO and depth pointcloud from stereo camera, is there a way to update it's internal map just using this information?

If yes, maybe you could point out some example code to do that?

Ideally, I also want to be able to delete points in the map, to maintain constant local map.

Thank you in advance.

Chang

**Comment by USTfgaoaa** [comment]
@Changliu52 Yes we have an isolated mapping module. 
You can check this repo : https://github.com/HKUST-Aerial-Robotics/VI-MEAN as well as related publications.
In our system, the mapping module maintains a global hashed voxel map, and in planning module I maintain a constant local map, just by filtering the voxels and keeping only voxels in a local range.

**Comment by Changliu52** [comment]
Great to know. Thanks Fei.
How do you suggest to interface the map generated by VI-MEAN with the grad_traj_optimization? I couldn't find any information on this.

Also, I noticed that VI-MEAN has its own self_calibration_estimator builtin. How is it compare against vinsmono? It doesn't seem to allow people to raise issue in the VI-MEAN repo.

Thanks again.

**Comment by USTfgaoaa** [comment]
@Changliu52 For the first question. grad_traj_optimization just provides a planning core, you have to write a map maintainer/interface for engineering usage. Basically, you'd better receive the voxels published by VI-MEAN and insert them into a local/global map.

For the second question, I think they are almost equivalent. The author of VI-MEAN also owns the authorship of a VI system which is the predecessor of vinmono and is used by our group.

**Comment by Changliu52** [comment]
OK. Cool! Thank you very much for the information.
