### ISSUE TITLE
some error  occured when performing catkin_make 

### ISSUE THREAD

**Issue by fighterxi** [HKUST-Aerial-Robotics/grad_traj_optimization#8]
Hi Gao,
Sorry to bother you, I have encountered the following problem， when i did the 'catkin_make -j1'.Ｉ use
ubunut14.04 \indigo \libboost1.54-dev. 
_________________________________________
Built target sdf_tools_generate_messages
[ 57%] Built target test_arc_utilities
[ 60%] Built target test_hierarchical_clustering
[ 63%] Building CXX object grad_traj_optimization/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/sdf.cpp.o
/home/relaybot/catkin_s0/src/grad_traj_optimization/third_party/sdf_tools/src/sdf_tools/sdf.cpp: In member function ‘double sdf_tools::SignedDistanceField::EstimateDistanceInternal(double, double, double, int64_t, int64_t, int64_t) const’:
/home/relaybot/catkin_s0/src/grad_traj_optimization/third_party/sdf_tools/src/sdf_tools/sdf.cpp:554:99: error: operands to ?: have different types ‘const Eigen::CwiseUnaryOp<Eigen::internal::scalar_opposite_op<double>, const Eigen::Matrix<double, 3, 1> >’ and ‘const Vector3d {aka const Eigen::Matrix<double, 3, 1>}’
         const Eigen::Vector3d direction_to_boundary = (nominal_sdf_distance >= 0.0) ? -gradient : gradient;
                                                                                                   ^
make[2]: *** [grad_traj_optimization/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/sdf.cpp.o] Error 1
make[1]: *** [grad_traj_optimization/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j3 -l3" failed
relaybot@ubuntu:~/catkin_s0$

**Comment by DiomandLEE** [comment]
Could you tell me how to deal with it？
