### ISSUE TITLE
can the algorithm be used in grid map？

### ISSUE THREAD

**Issue by sunhaoshui** [HKUST-Aerial-Robotics/grad_traj_optimization#9]
hello！I want to use this wonderful algorithm on the 2D grid map made by cartographer. Can you please give me some help on ？Thanks a lot！

**Comment by USTfgaoaa** [comment]
@sunhaoshui Hi haoshui,
Of course, it can be but may need modification by yourself. I will no longer maintain this repo, and further question you can directly send e-mail to Boyu: bzhouai@ust.hk

Best,
Fei
